version: '3.8'

services:
  app:
    container_name: codiga
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["node", "index.js"]
